# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

jobs:
- job: Linux

  pool:
    vmImage: 'ubuntu-latest'

  variables:
    solution: '**/*.sln'
    buildPlatform: 'Any CPU'
    buildConfiguration: 'Release'

  steps:
  - task: UseDotNet@2
    displayName: 'Install .NET Core sdk'
    inputs:
      packageType: sdk
      version: 2.1.803
      installationPath: $(Agent.ToolsDirectory)/dotnet
  - task: UseDotNet@2
    displayName: 'Install .NET Core sdk'
    inputs:
      packageType: sdk
      version: 3.1.402
      installationPath: $(Agent.ToolsDirectory)/dotnet
  - script: |
      set -e
      sudo pwsh -file patch-winfx.ps1 $(Agent.ToolsDirectory)/dotnet/sdk/3.1.402
      dotnet build SharpSnmpLib.Samples.sln --configuration $(buildConfiguration)
      dotnet test Tests/CSharpCore/Tests.NetStandard.csproj --configuration $(buildConfiguration) --no-build --framework netcoreapp2.1 --logger trx
      dotnet test Tests/CSharpCore/Tests.NetStandard.csproj --configuration $(buildConfiguration) --no-build --framework netcoreapp3.1 --logger trx
  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testRunner: VSTest
      testResultsFiles: '**/*.trx'

- job: macOS

  pool:
    vmImage: 'macOS-latest'

  variables:
    solution: '**/*.sln'
    buildPlatform: 'Any CPU'
    buildConfiguration: 'Release'

  steps:
  - task: UseDotNet@2
    displayName: 'Install .NET Core sdk'
    inputs:
      packageType: sdk
      version: 2.1.803
      installationPath: $(Agent.ToolsDirectory)/dotnet
  - task: UseDotNet@2
    displayName: 'Install .NET Core sdk'
    inputs:
      packageType: sdk
      version: 3.1.402
      installationPath: $(Agent.ToolsDirectory)/dotnet
  - script: |
      export CI=true
      set -e
      sudo pwsh -file patch-winfx.ps1 $(Agent.ToolsDirectory)/dotnet/sdk/3.1.402
      dotnet build SharpSnmpLib.Samples.sln --configuration $(buildConfiguration)
      dotnet test Tests/CSharpCore/Tests.NetStandard.csproj --configuration $(buildConfiguration) --no-build --framework netcoreapp2.1 --logger trx
      dotnet test Tests/CSharpCore/Tests.NetStandard.csproj --configuration $(buildConfiguration) --no-build --framework netcoreapp3.1 --logger trx
  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testRunner: VSTest
      testResultsFiles: '**/*.trx'

- job: Windows

  pool:
    vmImage: 'windows-latest'

  variables:
    solution: '**/*.sln'
    buildPlatform: 'Any CPU'
    buildConfiguration: 'Release'

  steps:
  - task: UseDotNet@2
    displayName: 'Install .NET Core sdk'
    inputs:
      packageType: sdk
      version: 2.1.803
      installationPath: $(Agent.ToolsDirectory)/dotnet
  - task: UseDotNet@2
    displayName: 'Install .NET Core sdk'
    inputs:
      packageType: sdk
      version: 3.1.402
      installationPath: $(Agent.ToolsDirectory)/dotnet
  - script: |
      build.release.bat
      dotnet test Tests/CSharpCore/Tests.NetStandard.csproj --configuration $(buildConfiguration) --no-build --framework netcoreapp2.1 --logger trx --collect "Code coverage"
      dotnet test Tests/CSharpCore/Tests.NetStandard.csproj --configuration $(buildConfiguration) --no-build --framework netcoreapp3.1 --logger trx --collect "Code coverage"
      dotnet test Tests/CSharpCore/Tests.NetStandard.csproj --configuration $(buildConfiguration) --no-build --framework net471 --logger trx --collect "Code coverage"
  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testRunner: VSTest
      testResultsFiles: '**/*.trx'
